#!/bin/bash
# This script executes some commands to figure out drifts 
# Uses original chart manifest to compare the changes that occured in the meantime !
# maintainer="serafettin.karatas@kobil.com"
workdir="/tmp/diff"
mkdir -p $workdir
date=$(date '+%Y-%m-%d_%H-%M-%S')
helm ls
for i in $(helm ls | awk '{ print $1 }'); do
  if [ $i == "NAME" ]; then
    printf "%s\n" "------------------------------------------------------------------------------"
    continue
  else
    echo "$i release is exists"
    printf "%s\n" "... writing $i original helm chart manifest file down"
    helm get manifest $i > $workdir/$i$date.yaml
   # $i$date.yam l
    printf "%s\n" "writing step is completed "
  fi
kubectl diff -f $workdir/$i$date.yaml > $workdir/diff_$i$date.yaml
case  $?  in
      0)
          echo "There is no diff. No manual changes! "
          printf "%s\n" "... seems OK "

          ;;
      1)
          echo "There is a diff.So be aware of the manual changes that were done after the helm chart deployment! "
          printf "%s\n" "Please look at the diff file ---> $workdir/diff_$i$date.yaml "
          ;;

      *)
          echo "this indicates an error. No panic but, you should do some examination "
esac
done
echo " ||| ---Diff Summary 4 All--- ||| "
 cat $workdir/diff_*$date.yaml | egrep  '(\-  |\+  )' > $workdir/diff_summary$date
 cat $workdir/diff_summary$date
